# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wolfgang
email: webmaster@ramosarhuis.de
description: > # this means to ignore newlines until "baseurl:"
  wolfgangs website
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ramosarhuis.de" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: WolfgangRamos

# Build settings
markdown: kramdown

# files to keep in the build directory
keep_files: [.git,.gitignore,CNAME]